language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  matrix:
    - LARAVEL=^6.0
    - LARAVEL=^7.0
    - LARAVEL=^8.0

matrix:
  fast_finish: true

install:
  - travis_retry composer require "illuminate/contracts=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - yangchenshin77@gmail.com
    on_success: never
    on_failure: always
